name: Build the presentation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          lfs: true

      - name: 📄 Compile the Demo Slides
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: slides.tex

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f "slides.pdf"
          git commit -m "Latest compiled data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
